[tool.black]
line-length = 100

[tool.isort]
profile = "black"
force_single_line = "True"

[tool.pylint.'BASIC']
good-names = ["ex", "fd"]

[tool.pylint.'MESSAGES CONTROL']
disable = ["too-many-arguments", "too-many-positional-arguments"]
