# This is a basic workflow to help you get started with Actions

name: DataRobot Custom Inference Models

# Controls when the workflow will run
on:
  workflow_run:
    workflows: [ Pull Request Validation ]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  datarobot-custom-inference-model:
    # Run this job on any action of a PR, but skip the job upon merge to master
    if: github.event.pull_request.merged != true && ${{ github.event.workflow_run.conclusion == 'success' }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: DataRobot Custom Inference Model
        id: custom-inference-model
        uses: ./actions/custom-inference-model
        with:
          api-token: ${{ secrets.DATAROBOT_API_TOKEN }}
          webserver: ${{ secrets.DATAROBOT_WEBSERVER }}
          main-branch: my-main-dev-branch

      - name: DataRobot Custom Inference Model Results
        run: |
          echo "Test result: ${{ steps.custom-inference-model.outputs.message }}"
          echo "Test result: ${{ steps.custom-inference-model.outputs.returned-code }}"
          echo "Test result: ${{ steps.custom-inference-model.outputs.test-result }}"
