name: DataRobot Workflow CI/CD

# Controls when the workflow will run
on:
  pull_request:
    branches: [ demo ]
  push:
    branches: [ demo ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  LOGLEVEL: debug

jobs:

  datarobot-custom-inference-model:
    # Run this job on any action of a PR, but skip the job upon merge to master. When a PR
    # is merged to the master the push even is also triggered.
    if: ${{ github.event.pull_request.merged != true }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: DataRobot Custom Inference Model
        id: datarobot-custom-inference-model
        # When referring to this action from another repository the 'uses' value will be changed
        # to this url: datarobot/custom-inference-model@v1.0.0
        uses: ./
        with:
          api-token: ${{ secrets.DATAROBOT_API_TOKEN }}
          webserver: ${{ secrets.DATAROBOT_WEBSERVER }}
          branch: demo
          allow-model-deletion: true
          allow-deployment-deletion: true
          skip-cert-verification: true

      - name: DataRobot Custom Inference Model Action Results
        run: |
          echo "Total affected models: ${{ steps.datarobot-custom-inference-model.outputs.total-affected-models }}"
          echo "Total created models: ${{ steps.datarobot-custom-inference-model.outputs.total-created-models }}"
          echo "Total deleted models: ${{ steps.datarobot-custom-inference-model.outputs.total-deleted-models }}"
          echo "Total created model versions: ${{ steps.datarobot-custom-inference-model.outputs.total-created-model-versions }}"

          echo "Total affected deployments: ${{ steps.datarobot-custom-inference-model.outputs.total-affected-deployments }}"
          echo "Total created deployments: ${{ steps.datarobot-custom-inference-model.outputs.total-created-deployments }}"
          echo "Total deleted deployments: ${{ steps.datarobot-custom-inference-model.outputs.total-deleted-deployments }}"

          echo "Message: ${{ steps.datarobot-custom-inference-model.outputs.message }}"
